Traceback (most recent call last):
  File "C:\Users\chjch\AppData\Local\ESRI\conda\envs\arcpro-py3-clone\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\chjch\AppData\Local\ESRI\conda\envs\arcpro-py3-clone\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\chjch\AppData\Local\ESRI\conda\envs\arcpro-py3-clone\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\chjch\AppData\Local\ESRI\conda\envs\arcpro-py3-clone\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\chjch\AppData\Local\ESRI\conda\envs\arcpro-py3-clone\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\chjch\AppData\Local\ESRI\conda\envs\arcpro-py3-clone\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\chjch\AppData\Local\ESRI\conda\envs\arcpro-py3-clone\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\chjch\AppData\Local\ESRI\conda\envs\arcpro-py3-clone\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
blkgrp_df = fc_to_df(blkgrp_fc)
blkgrp_df.head()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mOSError[0m                                   Traceback (most recent call last)
[1;32m<ipython-input-4-0a8773224bc3>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mblkgrp_df[0m [1;33m=[0m [0mfc_to_df[0m[1;33m([0m[0mblkgrp_fc[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mblkgrp_df[0m[1;33m.[0m[0mhead[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m<ipython-input-3-82cbfbedf196>[0m in [0;36mfc_to_df[1;34m(fc)[0m
[0;32m      1[0m [1;32mdef[0m [0mfc_to_df[0m[1;33m([0m[0mfc[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m     [0mfields[0m [1;33m=[0m [1;33m[[0m[0mfield[0m[1;33m.[0m[0mname[0m [1;32mfor[0m [0mfield[0m [1;32min[0m [0marcpy[0m[1;33m.[0m[0mListFields[0m[1;33m([0m[0mfc[0m[1;33m)[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m     [0marr[0m [1;33m=[0m [0marcpy[0m[1;33m.[0m[0mda[0m[1;33m.[0m[0mFeatureClassToNumPyArray[0m[1;33m([0m[0mfc[0m[1;33m,[0m [0mfields[0m[1;33m[[0m[1;36m2[0m[1;33m:[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m     [1;32mreturn[0m [0mpd[0m[1;33m.[0m[0mDataFrame[0m[1;33m([0m[0marr[0m[1;33m,[0m [0mcolumns[0m[1;33m=[0m[0mfields[0m[1;33m[[0m[1;36m2[0m[1;33m:[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py[0m in [0;36mListFields[1;34m(dataset, wild_card, field_type)[0m
[0;32m   1152[0m [1;33m[0m[0m
[0;32m   1153[0m         * String:   Only field types of String are returned."""
[1;32m-> 1154[1;33m     [1;32mreturn[0m [0mgp[0m[1;33m.[0m[0mlistFields[0m[1;33m([0m[0mdataset[0m[1;33m,[0m [0mwild_card[0m[1;33m,[0m [0mfield_type[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1155[0m [1;33m[0m[0m
[0;32m   1156[0m [1;33m@[0m[0m_gptooldoc[0m[1;33m([0m[1;32mNone[0m[1;33m,[0m [1;33m[[0m[1;33m[[0m[1;33m[[0m[1;34m"FeatureLayer"[0m[1;33m,[0m [1;34m"Table"[0m[1;33m,[0m [1;34m"TableView"[0m[1;33m,[0m [1;34m"Dataset"[0m[1;33m,[0m [1;34m"FeatureDataset"[0m[1;33m][0m[1;33m,[0m [1;34m""[0m[1;33m,[0m [1;34m""[0m[1;33m,[0m [1;34m""[0m[1;33m][0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py[0m in [0;36mlistFields[1;34m(self, *args)[0m
[0;32m    352[0m         [1;32mfrom[0m [0marcpy[0m[1;33m.[0m[0marcobjects[0m[1;33m.[0m[0marcobjectconversion[0m [1;32mimport[0m [0mconvertArcObjectToPythonObject[0m[1;33m[0m[1;33m[0m[0m
[0;32m    353[0m         return convertArcObjectToPythonObject(
[1;32m--> 354[1;33m                     self._gp.ListFields(*gp_fixargs(args, True)))
[0m[0;32m    355[0m     [1;32mdef[0m [0mlistIndexes[0m[1;33m([0m[0mself[0m[1;33m,[0m [1;33m*[0m[0margs[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    356[0m         [1;34m"""GP function ListIndexes"""[0m[1;33m[0m[1;33m[0m[0m

[1;31mOSError[0m: "blockgroups" does not exist
OSError: "blockgroups" does not exist

